// node tools/build-help.mjs [path to docs-content.js] — writes help-content.js, the articles of the Help window.
//
// The knowledge base is written once, for the website (lukagrcar.com/apps/meshoptimiser/docs, in the site's repo:
// apps/meshoptimiser/docs-content.js). This copies it into the app so Help works without a connection. Pictures stay
// on the website (the Help window loads them from there and hides one that cannot load). Run it again after the site's
// articles change, and bump the ?v= on help-content.js in help.js.
import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(process.argv[2] || path.join(HERE, '..', '..', 'Luka_site_v2', 'apps', 'meshoptimiser', 'docs-content.js'));
if (!fs.existsSync(src)) { console.error('Cannot find ' + src + '\nPass the path to the site\'s docs-content.js.'); process.exit(1); }
const docs = createRequire(import.meta.url)(src);

const data = {
  site: 'https://lukagrcar.com/',
  docs: 'https://lukagrcar.com/apps/meshoptimiser/docs.html',
  groups: docs.groups.map(g => ({ id: g.id, title: g.title, blurb: g.blurb })),
  articles: docs.articles.map(a => ({ slug: a.slug, group: a.group, title: a.title, summary: a.summary, blocks: a.blocks })),
};
const bad = data.articles.filter(a => !data.groups.some(g => g.id === a.group));
if (bad.length) throw new Error('articles in an unknown group: ' + bad.map(a => a.slug).join(', '));
const slugs = new Set(data.articles.map(a => a.slug));
for (const a of data.articles) for (const b of a.blocks) {
  if (b[0] === 'see') for (const s of b[1]) if (!slugs.has(s)) console.warn(`  ${a.slug}: "see" points to an article that does not exist: ${s}`);
}
const out = path.join(HERE, '..', 'help-content.js');
fs.writeFileSync(out, `// Generated by tools/build-help.mjs from the website's docs-content.js. Do not edit: edit the site's articles and run the builder again.\nwindow.MOHelpData = ${JSON.stringify(data)};\n`);
console.log(`help-content.js: ${data.articles.length} articles in ${data.groups.length} groups, ${(fs.statSync(out).size / 1024).toFixed(0)} KB`);
